### ISSUE TITLE
A silly question about slide generation

### ISSUE THREAD

**Issue by cheyang** [stevvooe/sillyproxy#1]
Hi,

May I know what tool you used to generate your beautiful deck from `present/swarm.slide`? It's cool! I searched a bit in google,  but failed to find it out. Thank you.

**Comment by stevvooe** [comment]
@cheyang This is [Go's present tool](https://godoc.org/golang.org/x/tools/present). Unfortunately, you can't just generate them. You must run the server against that directory.
