### ISSUE TITLE
Use this in production

### ISSUE THREAD

**Issue by galindro** [stevvooe/sillyproxy#3]
Is this project recommended to be use in production @stevvooe ?

Reading these posts: https://github.com/docker/swarmkit/issues/1045 and https://github.com/docker/docker/issues/26159, I see that it wasn't implemented in docker swarm mode yet and, based on the discussion, this project is the best approach to blue/green deployments in docker swarm mode.

**Comment by stevvooe** [comment]
Was https://github.com/stevvooe/sillyproxy#notes not descriptive enough? This example can be used to extrapolate a setup that works for you environment. This same approach could be done with nginx or apache or any other proxy. The key is to rotate deployment using rolling updates.
