### ISSUE TITLE
different ports between two different versions might not be a good idea

### ISSUE THREAD

**Issue by panol** [stevvooe/sillyproxy#4]
different published ports between two different versions might not be a good idea.Because in production,we may deploy many services on the same cluster and have some published ports,by adding a new published port will weight the management of the ports and even worse  other services will use the old version port,after you transfer the whole version to green,the blue version published port can not afford  service any longer,then the upstream of the service may fail to request to the service .

**Comment by stevvooe** [comment]
@lucas1993ch The different published ports are there to allow one to individually address the versions for demonstration.

Please don't use sillyproxy in production.

If I've misunderstood you, please send a PR correcting the mistake.
